### PR TITLE
the start of windows support

### PR DESCRIPTION
**Pull request by simonjefford**

### CODE REVIEW

**Comment by simonjefford** [comment]
I haven't tested this at all, just go it to (cross) compile (GOOS=windows go build)

**Comment by gpolaert** [comment]
Hi Simon,

I've made some tests with the hashicorp lib (gsyslog).
It's working ;) on Windows

I will release it soon.

**Comment by gpolaert** [comment]
I will merge and release this commit c5d344e847.
First tests are okay on windows

**Comment by gpolaert** [comment]
Duplicate with #3

**Pull request closed without merging**
